Controllers/AlgorythmController.cs
using Microsoft.AspNetCore.Mvc;
using System.Data;
using System.Security.Policy;
using url_shortener_service.Areas.Identity.Data;
using url_shortener_service.Models;

namespace url_shortener_service.Controllers
{
	public class AlgorythmController : Controller
	{

		private readonly ApplicationDbContext _context;
		public AlgorythmController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
		{
			return View();
		}


		private static string RandomString(int length)
		{
			Random random = new Random();
			const string chars = "ABCDEFHGIJKLMNOPQRSTUVWXYZ123456789";
			return new string(Enumerable.Repeat(chars, length)
				.Select(s => s[random.Next(s.Length)]).ToArray());
		}

		public IActionResult ShortUrl(url_shortener_service.Areas.Identity.Data.Url url)
		{
			url.ShortValue = RandomString(10);
			_context.Urls.Add(url);
			_context.SaveChanges();
			return View("GetUrl", url);
		}

		public IActionResult RedirectByUrl()
		{
			return View();
		}


		public IActionResult ForceRedirectByUrl(url_shortener_service.Areas.Identity.Data.Url url)
		{
			var shorturl = _context.Urls.FirstOrDefault(u => u.ShortValue == url.OriginValue);
			return Redirect(shorturl.OriginValue);

		}
	}
	


		
}
	

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - url_shortener_service</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/url_shortener_service.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">url_shortener_service</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Algorythm" asp-action="Index">URL Shortener</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Algorythm" asp-action="RedirectByUrl">Rerirect By Url</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Algorythm" asp-action="ShortUrlsTable">Short Urls Table</a>
                        </li>
                    </ul>
                </div>
                <partial name = "_LoginPartial"/>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - url_shortener_service - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>